[package]
name = "hs-benchmark-suite"
version = "0.2.2"
edition = "2021"

[dependencies]
sysinfo = "0.38"
libc = "0.2"
chrono = "0.4"

[[bin]]
name = "benchmark"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
